const int WID_INI = 700;
const int HEI_INI = 650;
const int INI_X = 350;
const int INI_Y = 70;
const int WC_R = 0.094;
const float WC_G = 0.157;
const float WC_B = 0.4;
const float WC_A = 1.0;
const float COORD_X = 10;
const float COORD_Y = 10;
const int SPACE_KEY = 32;
const int DEL_KEY = 8;
const int ENTER_KEY = 13;
const int ESC_KEY = 27;
const int TAB_KEY = 9;
const int lx = -0.7;
const int ly = -8;
const float CHAR_WIDTH = 0.2667;
const float DIM_FACTOR = 0.2;
const float CHECK_BOX_DIMENSION = 0.5;
int mainWindowIndex;
int WID;
int HEI;
long blinker = 0;
long blinkerT = 0;
long blinkerP = 0;
char CHAR_MASK = '*';
std::string userName = "";
std::string password = "";
std::string userNameN = "";
std::string passwordN = "";
std::vector<std::string> dataf = {"test1","test2","test3","test4","test5","test6","test7","test8","test9","test10","test11","test12","test13","test14","test15","test16","test17","test18","test19","test20","test21","test22","test23","test24","1","2","3","4","5","6","7"};
std::vector<std::string> books;
